exchange/urls.py
# /exchange/urls.py

from django.conf.urls import url

from .views import ExchangeCreateView, ExchangeDetailView

urlpatterns = [
    url(r'^$', ExchangeCreateView.as_view(), name='create_exchange'),
    url(r'^create/$', ExchangeCreateView.as_view(), name='create_exchange'),
    url(r'^detail/$', ExchangeDetailView.as_view(), name='exchange_detail'),
]

giftexchange/urls.py
# /giftexchange/urls.py

from django.conf.urls import include, url
from django.contrib import admin

from registration.backends.simple import urls as registrtation_urls

from exchange import urls as exchange_urls
from wishlist import urls as wishlist_urls

from . import views as home_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
	url(r'^$', home_views.HomeView.as_view(), name='home'),
    url(
        r'^accounts/register/$',
        home_views.CustomRegistrationView.as_view(),
        name='registration_register'
    ),
	url(r'^accounts/', include(registrtation_urls)),
    url(r'^wishlist/', include(wishlist_urls)),
    url(r'^profile/$', home_views.ProfileView.as_view(), name='profile'),
    url(r'^exchange/', include(exchange_urls)),
]

wishlist/urls.py
# /wishlist/urls.py

from django.conf.urls import url

from .views import WishlistCreateView, WishlistDetailView

urlpatterns = [
    url(r'create/$', WishlistCreateView.as_view(), name='create_wishlist'),
    url(
        r'detail/(?P<current_list>[0-9]+)/$',
        WishlistDetailView.as_view(),
        name='wishlist_detail'
    ),
]

wishlist/models.py
# /wishlist/models.py

from django.contrib.auth.models import User
from django.db import models



class Wishlist(models.Model):
    owner = models.ForeignKey(User)
    name = models.CharField(max_length=50, blank=False)
    
    
class WishlistItem(models.Model):
    wishlist = models.ForeignKey(Wishlist)
    description = models.CharField(max_length=100)
    link = models.URLField(max_length=200)
    claimed = models.BooleanField(default=False)
    

wishlist/forms.py
# /wishlist/forms.py

from django.forms import ModelForm

from crispy_forms.bootstrap import FormActions, InlineField, StrictButton
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Div, Field, Layout, Submit

from .models import Wishlist, WishlistItem


class WishlistForm(ModelForm):
    """Uses crispy forms helper to format the wishlist creation form"""
    class Meta:
        model = Wishlist
        fields = ['name']

    def __init__(self, *args, **kwargs):
        super(WishlistForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = 'id_wishlist_form'
        self.helper.form_class = 'form-horizontal'
        self.helper.form_method = 'post'
        self.helper.form_action = '/wishlist/create/'
        self.helper.label_class = 'col-md-2'
        self.helper.field_class = 'col-md-4'
        self.helper.layout = Layout(
            Div(
                'name', 
                FormActions(
                    Submit('submit', 'Create')
                ),
                css_class='container col-md-6 col-md-offset-4'
            ),
        )
        
        
        

class WishlistItemForm(ModelForm):
    """Uses crispy forms helper to format the item creation form"""
    class Meta:
        model = WishlistItem
        fields = ['description', 'link']
        
    def __init__(self, current_list=None, *args, **kwargs):
        super(WishlistItemForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = 'id_wishlist_item_form'
        self.helper.form_class = 'form-inline'
        self.helper.form_method = 'post'
        self.helper.form_action = '.'
        self.helper.layout = Layout(
            Div(
                Field('description', placeholder='Description'),
                Field('link', placeholder='Link to item'),
                StrictButton('Add', value='submit', type='submit', css_class='btn-default'),
                css_class='container col-md-6 col-md-offset-4'
            ),
        )

wishlist/views.py
# /wishlist/views.py

from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views.generic import ListView, TemplateView
from django.views.generic.detail import SingleObjectMixin
from django.views.generic.edit import CreateView, FormView

from braces.views import LoginRequiredMixin

from .forms import WishlistForm, WishlistItemForm
from .models import Wishlist, WishlistItem

class WishlistCreateView(LoginRequiredMixin, FormView):
    """
    Uses the FormView class to display the wishlist creation form and the
    LoginRequiredMixin mixin to make sure the user is authenticated
    """
        
    template_name = 'create_wishlist.html'
    form_class = WishlistForm
    success_url = '/profile/'
    login_url = '/accounts/login/'
    
    def form_valid(self, form):
        """
        Overrides the form_valid method to automatically save the current user
        as the owner of the new wishlist.
        """
        
        wishlist = form.save(commit=False)
        wishlist.owner = self.request.user
        wishlist.save()
        return HttpResponseRedirect(self.get_success_url())
        
    
        
class WishlistDetailView(LoginRequiredMixin, CreateView, SingleObjectMixin):
    """
    Uses the CreateView class and the SingleObjectMixin mixin to create new
    wishlist items. Used the LoginRequiredMixin mixin to ensure the user is 
    authenticated.
    """
    
    template_name = 'wishlist_detail.html'
    model = WishlistItem
    form_class = WishlistItemForm
    login_url = '/accounts/login/'
    
        
    def get(self, request, current_list):
        """
        Overrides the get method to expose the form and wishlist items for
        the current wishlist.
        """
        
        wishlist = Wishlist.objects.get(id=current_list)
        wishlistitems = wishlist.wishlistitem_set.all()
        form = self.form_class
        return render(request, 'wishlist_detail.html', {'form': form, 'wishlist': wishlist})
    
    def form_valid(self, form):
        """
        Overrides the form_valid method to automatically attach the current
        wishlist to the new item.
        """
        
        wishlist_item = form.save(commit=False)
        wishlist_item.wishlist = Wishlist.objects.get(
            id=self.kwargs['current_list']
        )
        wishlist_item.save()
        return HttpResponseRedirect(
            '/wishlist/detail/%s/' % (self.kwargs['current_list'],)
        )
        

templates/wishlist/create_wishlist.html
{# /templates/wishlist/create_wishlist.html #}

{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% crispy new_wishlist new_wishlist.helper %}

{% block title_text %}Wishlist Creation{% endblock %}

{% block header_text %}Create a Wishlist{% endblock %}

{% block content %}

{% crispy form %}

{% endblock %}

templates/wishlist/wishlist_detail.html
{# /templates/wishlist/wishlist_detail.html #}

{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% crispy new_wishlist new_wishlist.helper %}

{% block title_text %}Profile{% endblock %}

{% block header_text %}Your Profile{% endblock %}

{% block content %}
    <div class="container col-md-6 col-md-offset-4">
        <ul>
        {% for item in wishlist.wishlistitem_set.all %}
            <li>{{item.description}} <a href="{{item.link}}">Link</a></li>
        {% endfor %}
        </ul>
    </div>
    <br>
    {% crispy form %}
{% endblock %}

templates/wishlist/wishlist_list.html
{# /templates/wishlist/wishlist_list.html #}

{% extends 'base.html' %}

{% block title_text %}Profile{% endblock %}

{% block header_text %}Your Profile{% endblock %}

{% block content %}
    <div class="container col-md-4 col-md-offset-4">
        <ul>
        {% for wishlist in owner.wishlist_set.all %}
            <li>{{wishlist.name}} <a href="{% url 'wishlist_detail' wishlist.id %}">View</a></li>
        {% endfor %}
            <li>Create a Wishlist <a href="{% url 'create_wishlist' %}">Create</a></li>
        </ul>
    </div>
{% endblock %}

{% block scripts %}
    <script>
        $(document).ready(function () {
            $("#id_profile_navbar").attr('class', 'active');
        });
    </script>
{% endblock %}